### ISSUE TITLE
Task List!

### ISSUE THREAD

**Issue by svb-hikip** [svb-hikip/hikipfe-react#3]
- [ ] http://localhost:5173/dashboard/clients - When the client list is loading, suspense is required to be added? 
- [ ] http://localhost:5173/dashboard/clients/fc05d31a-747e-428f-a185-13d00423775c/appointments - This clients details page needs to be improved
- [ ] http://localhost:5173/dashboard/clients/fc05d31a-747e-428f-a185-13d00423775c/bills - This bills page needs to be improved
- [ ] http://localhost:5173/dashboard/clients/fc05d31a-747e-428f-a185-13d00423775c/notes - The client notes are to be displayed properly. https://tiptap.dev/ Tiptap is to be used for WYSIWYG editor for adding / editing notes
- [x] Appointment Detail page to be created
- [x] Bill detail page to be created (Invoice details)
- [x] http://localhost:5173/dashboard/appointments - Appointments, on clicking Appointments the appointment details to be displayed.
- [ ] Forms to be created for Adding appointment
- [ ] Forms to be created for Adding bill
